grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
    refit: roc_auc_ovr
    scoring: [accuracy, roc_auc_ovr]
model_selection:
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      random_state: 2023
    search_param_grid:
      n_estimators: [50,100,200]
      min_samples_split: [2,5,10]
      min_samples_leaf: [1,3,5]
      criterion: ['gini', 'entropy']
      max_depth: [4,6,8]
      max_features: ['sqrt', 'log2']
      class_weight: ['balanced']
      ccp_alpha: [0.0, 0.01]

  module_2:
    class: XGBClassifier
    module: xgboost
    params:
      random_state: 2023
    search_param_grid:
      n_estimators: [50, 100]
      max_depth: [3, 4]
      learning_rate: [0.05, 0.1]
      subsample: [0.8]
      colsample_bytree: [0.8]
      gamma: [0, 0.1]
      reg_alpha: [0, 0.1]
      reg_lambda: [0, 0.1]
      min_child_weight: [1, 3]

