columns:
  age: float
  sex: category
  on thyroxine: category
  query on thyroxine: category
  on antithyroid medication: category
  sick: category
  pregnant: category
  thyroid surgery: category
  I131 treatment: category
  query hypothyroid: category
  query hyperthyroid: category
  lithium: category
  goitre: category
  tumor: category
  hypopituitary: category
  psych: category
  TSH: float
  T3: float
  TT4: float
  T4U: float
  FTI: float
  Class: category

  
numerical_columns:
  -  age
  -  TSH
  -  T3
  -  TT4
  -  T4U
  -  FTI


categorical_columns:
  -  sex
  -  on thyroxine
  -  query on thyroxine
  -  on antithyroid medication
  -  sick
  -  pregnant
  -  thyroid surgery
  -  I131 treatment
  -  query hypothyroid
  -  query hyperthyroid
  -  lithium
  -  goitre
  -  tumor
  -  hypopituitary
  -  psych


target_column: Class

domain_value:
  sex:
    - M
    - F
  on thyroxine:
    - t
    - f
  query on thyroxine:
    - t
    - f
  on antithyroid medication:
    - t
    - f
  sick:
    - t
    - f
  pregnant:
    - t
    - f
  thyroid surgery:
    - t
    - f
  I131 treatment:
    - t
    - f
  query hypothyroid:
    - t
    - f
  query hyperthyroid:
    - t
    - f
  lithium:
    - t
    - f
  goitre:
    - t
    - f
  tumor:
    - t
    - f
  hypopituitary:
    - t
    - f
  psych:
    - t
    - f
  Class:
    - negative
    - hyperthyroidism
    - hypothyroidism